title: My-first-dash
description: My-first-dash-Elise-56
template:
  repo: my-first-dash-template
  name: my-first-dash
before:
  - type: createIssue
    title: Welcome!
    body: new-issue.md
steps:
  - title: First step
    description: The first step in your course
    event: issues.assigned
    link: '{{ repoUrl }}'
    actions:
      - type: closeIssue
